<?php

use yii\db\Migration;

class m170515_131954_classifications extends Migration
{
    public function up()
    {
        $tables = Yii::$app->db->schema->getTableNames();
        $dbType = $this->db->driverName;
        $tableOptions_mysql = "CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB";
        $tableOptions_mssql = "";
        $tableOptions_pgsql = "";
        $tableOptions_sqlite = "";
        /* MYSQL */
        if (!in_array('api_classifications', $tables))  { 
        if ($dbType == "mysql") {
            $this->createTable('{{%api_classifications}}', [
                'unique_id' => 'INT(11) NOT NULL AUTO_INCREMENT',
                0 => 'PRIMARY KEY (`unique_id`)',
                'id' => 'VARCHAR(25) NULL',
                'scheme' => 'VARCHAR(255) NOT NULL',
                'description' => 'TEXT NULL',
                'uri' => 'INT(11) NULL',
            ], $tableOptions_mysql);
        }
        }
         
         
        $this->createIndex('idx_id_7562_00','api_classifications','id',0);
         
        $this->execute('SET foreign_key_checks = 0');
        $this->insert('{{%api_classifications}}',['unique_id'=>'2','id'=>'07223000-8','scheme'=>'CAV','description'=>'Застава - Земельні ділянки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'3','id'=>'07120000-6','scheme'=>'CAV','description'=>'Кредити Юридичних осіб заставні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'4','id'=>'07000000-9','scheme'=>'CAV','description'=>'Права вимоги за кредитними договорами','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'5','id'=>'07110000-3','scheme'=>'CAV','description'=>'Кредити Юридичних осіб беззаставні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'6','id'=>'04000000-8','scheme'=>'CAV','description'=>'Нерухоме майно','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'7','id'=>'30100000-0','scheme'=>'CAV','description'=>'Офісні техніка, устаткування та приладдя, крім комп’ютерів, принтерів та меблів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'8','id'=>'39700000-9','scheme'=>'CAV','description'=>'Побутова техніка','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'9','id'=>'07100000-0','scheme'=>'CAV','description'=>'Кредити Юридичних осіб','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'10','id'=>'04111100-0','scheme'=>'CAV','description'=>'Квартира','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'11','id'=>'39714110-4','scheme'=>'CAV','description'=>'Витяжні вентилятори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'12','id'=>'04111000-9','scheme'=>'CAV','description'=>'Квартира в будинку малоповерхового житлового будівництва','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'13','id'=>'30123200-9','scheme'=>'CAV','description'=>'Банкомати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'14','id'=>'04111200-1','scheme'=>'CAV','description'=>'Таунхаус','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'15','id'=>'30000000-9','scheme'=>'CAV','description'=>'Офісна та комп’ютерна техніка, устаткування та приладдя, крім меблів та пакетів програмного забезпечення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'16','id'=>'30131600-2','scheme'=>'CAV','description'=>'Пристрої для заклеювання конвертів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'17','id'=>'39143100-7','scheme'=>'CAV','description'=>'Меблі для спальні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'18','id'=>'42700000-3','scheme'=>'CAV','description'=>'Машини для виробництва текстильних виробів, одягу та шкіряних виробів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'19','id'=>'34500000-2','scheme'=>'CAV','description'=>'Судна та човни','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'20','id'=>'39114100-5','scheme'=>'CAV','description'=>'Оббивка','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'21','id'=>'39722000-9','scheme'=>'CAV','description'=>'Частини печей, кухонних плит, підігрівачів тарілок та інших побутових приладів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'22','id'=>'34111000-8','scheme'=>'CAV','description'=>'Легкові автомобілі типів «універсал» та «седан»','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'23','id'=>'34933000-6','scheme'=>'CAV','description'=>'Навігаційне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'24','id'=>'42417200-4','scheme'=>'CAV','description'=>'Конвеєри','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'25','id'=>'16613000-5','scheme'=>'CAV','description'=>'Машини для очищення, сортування чи калібрування насіння, зерна чи сушених овочів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'26','id'=>'42414410-8','scheme'=>'CAV','description'=>'Крани-маніпулятори для вантажних автомобілів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'27','id'=>'42124150-7','scheme'=>'CAV','description'=>'Частини гідравлічних двигунів або моторів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'28','id'=>'04100000-9','scheme'=>'CAV','description'=>'Житлова  нерухомість','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'29','id'=>'39713211-5','scheme'=>'CAV','description'=>'Сушильні та прасувальні прилади','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'30','id'=>'16540000-2','scheme'=>'CAV','description'=>'Сільськогосподарські розвантажувальні напівпричепи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'31','id'=>'04222000-0','scheme'=>'CAV','description'=>'магазин (гастроном, універмаг, мінімаркет), аптека, перукарня, хімчистка, пральня, лікарняно-оздоровчий заклад, фізкультурно-оздоровчий заклад тощо','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'32','id'=>'05000000-5','scheme'=>'CAV','description'=>'Цілісний майновий комплекс або майновий комплекс - комплекс активів підприємства ','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'33','id'=>'06000000-2','scheme'=>'CAV','description'=>'Земельні ділянки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'34','id'=>'07122000-0','scheme'=>'CAV','description'=>'Застава - Цілісний майновий комплекс або майновий комплекс - комплекс активів підприємства ','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'35','id'=>'34321100-4','scheme'=>'CAV','description'=>'Осі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'36','id'=>'42418930-7','scheme'=>'CAV','description'=>'Навантажувачі з бічним висувним вантажопідіймачем','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'37','id'=>'04112100-7','scheme'=>'CAV','description'=>'Квартира','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'38','id'=>'30216100-7','scheme'=>'CAV','description'=>'Оптичні зчитувальні пристрої','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'39','id'=>'16710000-5','scheme'=>'CAV','description'=>'Мотоблоки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'40','id'=>'34969100-8','scheme'=>'CAV','description'=>'Літакові телескопічні трапи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'41','id'=>'39226100-3','scheme'=>'CAV','description'=>'Футляри для пляшок','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'42','id'=>'42997100-2','scheme'=>'CAV','description'=>'Машини для перевірки внутрішніх поверхонь трубопроводів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'43','id'=>'39292500-0','scheme'=>'CAV','description'=>'Лінійки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'44','id'=>'04112200-8','scheme'=>'CAV','description'=>'Пентхаус','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'45','id'=>'05020000-1','scheme'=>'CAV','description'=>'АЗС (автоматичні заправні станції)','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'46','id'=>'30237280-5','scheme'=>'CAV','description'=>'Пристрої електроживлення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'47','id'=>'34928220-6','scheme'=>'CAV','description'=>'Частини огорожі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'48','id'=>'39541110-0','scheme'=>'CAV','description'=>'Мотузки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'49','id'=>'42350000-4','scheme'=>'CAV','description'=>'Кремаційні печі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'50','id'=>'07121000-3','scheme'=>'CAV','description'=>'Застава - Нерухоме майно','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'51','id'=>'39292100-6','scheme'=>'CAV','description'=>'Класні дошки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'52','id'=>'39713430-6','scheme'=>'CAV','description'=>'Пилососи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'53','id'=>'42990000-2','scheme'=>'CAV','description'=>'Машини спеціального призначення різні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'54','id'=>'42122440-3','scheme'=>'CAV','description'=>'Роторні насоси','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'55','id'=>'39533000-7','scheme'=>'CAV','description'=>'Килими','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'56','id'=>'30237260-9','scheme'=>'CAV','description'=>'Настінні кронштейни для моніторів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'57','id'=>'30197510-4','scheme'=>'CAV','description'=>'Приладдя для користування сургучем','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'58','id'=>'30233130-1','scheme'=>'CAV','description'=>'Накопичувачі на магнітних дисках','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'59','id'=>'42412100-8','scheme'=>'CAV','description'=>'Шахтові лебідки та лебідки для підземних гірничих робіт','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'60','id'=>'42931140-4','scheme'=>'CAV','description'=>'Обертові механізми для центрифуг','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'61','id'=>'34972000-1','scheme'=>'CAV','description'=>'Системи вимірювання транспортного потоку','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'62','id'=>'42912300-5','scheme'=>'CAV','description'=>'Машини та апарати для фільтрування чи очищення води','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'63','id'=>'42131142-0','scheme'=>'CAV','description'=>'Регулювальні клапани','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'64','id'=>'32441300-9','scheme'=>'CAV','description'=>'Телематичні системи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'65','id'=>'16400000-9','scheme'=>'CAV','description'=>'Обприскувальні апарати для використання у сільському господарстві та рослинництві','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'66','id'=>'34223340-1','scheme'=>'CAV','description'=>'Причепи-цистерни','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'67','id'=>'32341000-5','scheme'=>'CAV','description'=>'Мікрофони','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'68','id'=>'30199330-2','scheme'=>'CAV','description'=>'Паперова стрічка для комп’ютерних принтерів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'69','id'=>'39221123-5','scheme'=>'CAV','description'=>'Стакани','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'70','id'=>'42131210-8','scheme'=>'CAV','description'=>'Засувки ножові ','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'71','id'=>'32541000-7','scheme'=>'CAV','description'=>'Комутаційне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'72','id'=>'30237251-3','scheme'=>'CAV','description'=>'Набори для очищення комп’ютерного обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'73','id'=>'34722200-6','scheme'=>'CAV','description'=>'Дирижаблі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'74','id'=>'04112000-6','scheme'=>'CAV','description'=>'квартира в будинку багатоповерхового житлового будівництва','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'75','id'=>'34410000-4','scheme'=>'CAV','description'=>'Мотоцикли','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'76','id'=>'42419890-1','scheme'=>'CAV','description'=>'Частини ківшових конвеєрів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'77','id'=>'32581200-1','scheme'=>'CAV','description'=>'Факсимільне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'78','id'=>'39225500-0','scheme'=>'CAV','description'=>'Піротехнічні вироби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'79','id'=>'34311110-4','scheme'=>'CAV','description'=>'Двигуни з іскровим запалюванням','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'80','id'=>'39113700-4','scheme'=>'CAV','description'=>'Підставки для ніг','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'81','id'=>'39541200-8','scheme'=>'CAV','description'=>'Текстильні сітки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'82','id'=>'42511000-1','scheme'=>'CAV','description'=>'Теплообмінники та обладнання для скраплення повітря чи інших газів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'83','id'=>'39151000-5','scheme'=>'CAV','description'=>'Меблі різні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'84','id'=>'42964000-1','scheme'=>'CAV','description'=>'Обладнання для автоматизації офісу','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'85','id'=>'42997000-1','scheme'=>'CAV','description'=>'Меблі (у тому числі офісні меблі), меблево-декоративні вироби, побутова техніка (крім освітлювального обладнання) та засоби для чищення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'86','id'=>'34432000-4','scheme'=>'CAV','description'=>'Частини та приладдя до велосипедів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'87','id'=>'39155100-4','scheme'=>'CAV','description'=>'Бібліотечне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'88','id'=>'30170000-1','scheme'=>'CAV','description'=>'Етикетувальні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'89','id'=>'34312300-0','scheme'=>'CAV','description'=>'Автомобільні радіатори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'90','id'=>'32342300-5','scheme'=>'CAV','description'=>'Мікрофони та звукові колонки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'91','id'=>'39831200-8','scheme'=>'CAV','description'=>'Мийні засоби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'92','id'=>'34224200-5','scheme'=>'CAV','description'=>'Частини інших транспортних засобів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'93','id'=>'39830000-9','scheme'=>'CAV','description'=>'Продукція для чищення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'94','id'=>'34968100-1','scheme'=>'CAV','description'=>'Аеропортові системи спостереження','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'95','id'=>'32342411-6','scheme'=>'CAV','description'=>'Акустичні мініатюрні системи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'96','id'=>'42932000-8','scheme'=>'CAV','description'=>'Вальцювальні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'97','id'=>'30123620-9','scheme'=>'CAV','description'=>'Автомати для рахування монет','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'98','id'=>'34144730-4','scheme'=>'CAV','description'=>'Авіазаправні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'99','id'=>'34114120-6','scheme'=>'CAV','description'=>'Санітарні транспортні засоби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'100','id'=>'32340000-8','scheme'=>'CAV','description'=>'Мікрофони та гучномовці','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'101','id'=>'30234300-1','scheme'=>'CAV','description'=>'Компакт-диски (CD)','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'102','id'=>'39541140-9','scheme'=>'CAV','description'=>'Шпагати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'103','id'=>'30122200-2','scheme'=>'CAV','description'=>'Цифрове обладнання для офсетного друку','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'104','id'=>'04233000-0','scheme'=>'CAV','description'=>'адміністративні приміщення в житлових будинках','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'105','id'=>'04231000-6','scheme'=>'CAV','description'=>'бізнес-центр, приміщення в бізнес-центрі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'106','id'=>'30123630-2','scheme'=>'CAV','description'=>'Автомати для пакування монет','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'107','id'=>'34114122-0','scheme'=>'CAV','description'=>'Транспортні засоби для перевезення пацієнтів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'108','id'=>'42673000-4','scheme'=>'CAV','description'=>'Ділильні голівки для верстатів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'109','id'=>'39299200-6','scheme'=>'CAV','description'=>'Безпечне скло','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'110','id'=>'34111100-9','scheme'=>'CAV','description'=>'Легкові автомобілі типу «універсал»','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'111','id'=>'34000000-7','scheme'=>'CAV','description'=>'Транспортне обладнання та допоміжне приладдя до нього','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'112','id'=>'42512520-9','scheme'=>'CAV','description'=>'Вентиляційні жалюзійні ґрати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'113','id'=>'42122400-1','scheme'=>'CAV','description'=>'Відцентрові насоси та підіймачі рідин','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'114','id'=>'30199760-5','scheme'=>'CAV','description'=>'Етикетки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'115','id'=>'30199762-9','scheme'=>'CAV','description'=>'Багажні ярлики','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'116','id'=>'34722000-4','scheme'=>'CAV','description'=>'Аеростати та дирижаблі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'117','id'=>'42122460-9','scheme'=>'CAV','description'=>'Повітряні насоси','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'118','id'=>'30194700-2','scheme'=>'CAV','description'=>'Трафарети','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'119','id'=>'30233141-1','scheme'=>'CAV','description'=>'Надлишковий масив незалежних дисків (RAID)','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'120','id'=>'04220000-6','scheme'=>'CAV','description'=>'Торгова нерухомість','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'121','id'=>'16120000-2','scheme'=>'CAV','description'=>'Борони, скарифікатори, культиватори, прополювачі або розпушувачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'122','id'=>'42716000-8','scheme'=>'CAV','description'=>'Пральні машини, машини для сухого чищення та сушильні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'123','id'=>'30194000-5','scheme'=>'CAV','description'=>'Креслярське приладдя','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'124','id'=>'39225200-7','scheme'=>'CAV','description'=>'Пірофорні сплави','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'125','id'=>'34320000-6','scheme'=>'CAV','description'=>'Механічні запасні частини, крім двигунів і частин двигунів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'126','id'=>'42414220-9','scheme'=>'CAV','description'=>'Мостові крани','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'127','id'=>'34138000-3','scheme'=>'CAV','description'=>'Автотягачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'128','id'=>'32000000-3','scheme'=>'CAV','description'=>'Радіо-, телевізійна, комунікаційна, телекомунікаційна та супутня апаратура й обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'129','id'=>'30233110-5','scheme'=>'CAV','description'=>'Накопичувачі на магнітних картках','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'130','id'=>'30124510-2','scheme'=>'CAV','description'=>'Імпринтери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'131','id'=>'30163000-9','scheme'=>'CAV','description'=>'Платіжні картки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'132','id'=>'42641300-4','scheme'=>'CAV','description'=>'Верстати для обробки бетону','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'133','id'=>'42641000-1','scheme'=>'CAV','description'=>'Верстати для обробки каменю, кераміки, бетону чи скла','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'134','id'=>'34996000-5','scheme'=>'CAV','description'=>'Регулювальне, запобіжне чи сигнальне дорожнє обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'135','id'=>'39151100-6','scheme'=>'CAV','description'=>'Стелажі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'136','id'=>'34211100-0','scheme'=>'CAV','description'=>'Кузови автобусів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'137','id'=>'30199240-4','scheme'=>'CAV','description'=>'Поштові набори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'138','id'=>'42211100-9','scheme'=>'CAV','description'=>'Відцентрові сепаратори вершків','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'139','id'=>'42511100-2','scheme'=>'CAV','description'=>'Теплообмінники','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'140','id'=>'30231310-3','scheme'=>'CAV','description'=>'Плоскопанельні дисплеї','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'141','id'=>'42151000-9','scheme'=>'CAV','description'=>'Ядерні реактори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'142','id'=>'42512510-6','scheme'=>'CAV','description'=>'Зволожувачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'143','id'=>'30234200-0','scheme'=>'CAV','description'=>'Оптичні диски','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'144','id'=>'39143110-0','scheme'=>'CAV','description'=>'Ліжка та спальне приладдя і домашній текстиль','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'145','id'=>'32342420-2','scheme'=>'CAV','description'=>'Студійні мікшувальні пульти','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'146','id'=>'32552420-7','scheme'=>'CAV','description'=>'Перетворювачі частоти','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'147','id'=>'16000000-5','scheme'=>'CAV','description'=>'Сільськогосподарська техніка','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'148','id'=>'32333200-8','scheme'=>'CAV','description'=>'Камкодери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'149','id'=>'42662200-6','scheme'=>'CAV','description'=>'Обладнання для неелектричного зварювання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'150','id'=>'42124212-0','scheme'=>'CAV','description'=>'Частини ручних насосів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'151','id'=>'06080000-6','scheme'=>'CAV','description'=>'Землі лісогосподарського призначення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'152','id'=>'39722300-2','scheme'=>'CAV','description'=>'Частини підігрівачів тарілок','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'153','id'=>'39110000-6','scheme'=>'CAV','description'=>'Сидіння, стільці та супутні вироби і частини до них','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'154','id'=>'34115300-9','scheme'=>'CAV','description'=>'Транспортні засоби, що були у використанні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'155','id'=>'39292200-7','scheme'=>'CAV','description'=>'Грифельні дошки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'156','id'=>'42996300-7','scheme'=>'CAV','description'=>'Шкребла','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'157','id'=>'32552400-1','scheme'=>'CAV','description'=>'Пристрої перетворення сигналів звукових частот','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'158','id'=>'39711420-9','scheme'=>'CAV','description'=>'Варильні поверхні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'159','id'=>'34421000-4','scheme'=>'CAV','description'=>'Моторолери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'160','id'=>'42912000-2','scheme'=>'CAV','description'=>'Машини та апарати для фільтрування чи очищення рідин','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'161','id'=>'39132000-6','scheme'=>'CAV','description'=>'Шафи-картотеки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'162','id'=>'34522550-2','scheme'=>'CAV','description'=>'Каное','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'163','id'=>'42131150-9','scheme'=>'CAV','description'=>'Клапани стояків','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'164','id'=>'39516000-2','scheme'=>'CAV','description'=>'Предмети декору','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'165','id'=>'42417220-0','scheme'=>'CAV','description'=>'Стрічкові елеватори чи конвеєри безперервної дії','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'166','id'=>'42953000-1','scheme'=>'CAV','description'=>'Частини вальцювальних машин','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'167','id'=>'34928200-0','scheme'=>'CAV','description'=>'Огорожі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'168','id'=>'30121420-3','scheme'=>'CAV','description'=>'Офісні комбайни','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'169','id'=>'39534000-4','scheme'=>'CAV','description'=>'Промислові ковроліни','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'170','id'=>'04113000-3','scheme'=>'CAV','description'=>'Елінг','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'171','id'=>'39153000-9','scheme'=>'CAV','description'=>'Меблі для конференц-зал','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'172','id'=>'42611000-2','scheme'=>'CAV','description'=>'Верстати спеціального призначення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'173','id'=>'32442100-4','scheme'=>'CAV','description'=>'Контактні плати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'174','id'=>'42122430-0','scheme'=>'CAV','description'=>'Відцентрові насоси','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'175','id'=>'42112100-5','scheme'=>'CAV','description'=>'Парові турбіни','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'176','id'=>'42511200-3','scheme'=>'CAV','description'=>'Обладнання для скраплення повітря чи інших газів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'177','id'=>'34992000-7','scheme'=>'CAV','description'=>'Вказівники та світлові вказівники','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'178','id'=>'39155000-3','scheme'=>'CAV','description'=>'Бібліотечні меблі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'179','id'=>'32320000-2','scheme'=>'CAV','description'=>'Телевізійне й аудіовізуальне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'180','id'=>'42621000-5','scheme'=>'CAV','description'=>'Токарні верстати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'181','id'=>'39522130-7','scheme'=>'CAV','description'=>'Маркізи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'182','id'=>'34522300-5','scheme'=>'CAV','description'=>'Малі судна','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'183','id'=>'30192123-9','scheme'=>'CAV','description'=>'Ручки-маркери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'184','id'=>'30232120-1','scheme'=>'CAV','description'=>'Матричні принтери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'185','id'=>'42122500-2','scheme'=>'CAV','description'=>'Лабораторні насоси та приладдя до них','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'186','id'=>'42123300-7','scheme'=>'CAV','description'=>'Компресори до холодильного устаткування','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'187','id'=>'32344220-4','scheme'=>'CAV','description'=>'Радіопейджери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'188','id'=>'39370000-6','scheme'=>'CAV','description'=>'Водопровідне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'189','id'=>'30236120-9','scheme'=>'CAV','description'=>'Постійні запам’ятовувальні пристрої (ROM)','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'190','id'=>'04230000-9','scheme'=>'CAV','description'=>'Адміністративно-офісна нерухомість','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'191','id'=>'32343000-9','scheme'=>'CAV','description'=>'Підсилювачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'192','id'=>'32344250-3','scheme'=>'CAV','description'=>'Радіоустановки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'193','id'=>'30237270-2','scheme'=>'CAV','description'=>'Сумки для портативних комп’ютерів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'194','id'=>'42713000-7','scheme'=>'CAV','description'=>'Ткацькі верстати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'195','id'=>'42412110-1','scheme'=>'CAV','description'=>'Шахтні лебідки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'196','id'=>'30199000-0','scheme'=>'CAV','description'=>'Паперове канцелярське приладдя та інші паперові вироби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'197','id'=>'34144440-4','scheme'=>'CAV','description'=>'Снігоприбиральні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'198','id'=>'39714100-1','scheme'=>'CAV','description'=>'Вентилятори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'199','id'=>'42981000-6','scheme'=>'CAV','description'=>'Озоногенератори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'200','id'=>'39541100-7','scheme'=>'CAV','description'=>'Шпагати, канати та мотузки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'201','id'=>'07200000-1','scheme'=>'CAV','description'=>'Кредити Фізичних осіб','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'202','id'=>'30192154-5','scheme'=>'CAV','description'=>'Змінні подушки для штампів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'203','id'=>'42113190-9','scheme'=>'CAV','description'=>'Поворотні механізми','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'204','id'=>'39811100-1','scheme'=>'CAV','description'=>'Освіжувачі повітря','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'205','id'=>'30237330-1','scheme'=>'CAV','description'=>'Картриджі цифрової аудіострічки (DAT-картриджі)','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'206','id'=>'42131140-6','scheme'=>'CAV','description'=>'Редукційні, регулювальні, зворотні та запобіжні клапани','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'207','id'=>'42632000-5','scheme'=>'CAV','description'=>'Металообробні верстати з числовим програмник керуванням','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'208','id'=>'34993100-5','scheme'=>'CAV','description'=>'Системи освітлення тунелів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'209','id'=>'30173000-2','scheme'=>'CAV','description'=>'Автомати для наклеювання етикеток','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'210','id'=>'30197500-1','scheme'=>'CAV','description'=>'Сургуч','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'211','id'=>'30195921-4','scheme'=>'CAV','description'=>'Гумки для магнітних дощок','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'212','id'=>'32251100-8','scheme'=>'CAV','description'=>'Гарнітури «вільні руки»','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'213','id'=>'39162000-5','scheme'=>'CAV','description'=>'Приладдя для навчальних закладів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'214','id'=>'34946100-1','scheme'=>'CAV','description'=>'Конструкційні матеріали для залізничних колій','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'215','id'=>'34351000-2','scheme'=>'CAV','description'=>'Шини для транспортних засобів малої тоннажності','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'216','id'=>'34113100-3','scheme'=>'CAV','description'=>'Джипи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'217','id'=>'42941000-4','scheme'=>'CAV','description'=>'Машини для термічної обробки газів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'218','id'=>'34113000-2','scheme'=>'CAV','description'=>'Повнопривідні транспортні засоби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'219','id'=>'30194800-3','scheme'=>'CAV','description'=>'Рейсшини та косинці','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'220','id'=>'34144751-7','scheme'=>'CAV','description'=>'Портові навантажувачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'221','id'=>'42200000-8','scheme'=>'CAV','description'=>'Машини для обробки продуктів харчування, виробництва напоїв та обробки тютюну','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'222','id'=>'42677000-2','scheme'=>'CAV','description'=>'Частини пневматичних інструментів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'223','id'=>'34521300-8','scheme'=>'CAV','description'=>'Поліцейські патрульні катери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'224','id'=>'34631000-9','scheme'=>'CAV','description'=>'Частини локомотивів чи рухомого складу','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'225','id'=>'39113400-1','scheme'=>'CAV','description'=>'Шезлонги','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'226','id'=>'16100000-6','scheme'=>'CAV','description'=>'Сільськогосподарські та лісогосподарські машини для підготовки або обробки ґрунту','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'227','id'=>'34622500-8','scheme'=>'CAV','description'=>'Багажні вагони та вагони спеціального призначення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'228','id'=>'30192500-6','scheme'=>'CAV','description'=>'Прозорі плівки для графопроекторів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'229','id'=>'39134100-1','scheme'=>'CAV','description'=>'Комп’ютерні столи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'230','id'=>'34997100-3','scheme'=>'CAV','description'=>'Бортові самописці','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'231','id'=>'39298500-2','scheme'=>'CAV','description'=>'Оздоби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'232','id'=>'32321200-1','scheme'=>'CAV','description'=>'Аудіовізуальне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'233','id'=>'04213000-4','scheme'=>'CAV','description'=>'гараж, станція технічного обслуговування, мийка транспортних засобів, автостоянка, автозаправна станція тощо та їх частини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'234','id'=>'30231100-8','scheme'=>'CAV','description'=>'Комп’ютерні термінали','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'235','id'=>'30151000-2','scheme'=>'CAV','description'=>'Електронні друкарські машинки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'236','id'=>'34411200-3','scheme'=>'CAV','description'=>'Шини для мотоциклів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'237','id'=>'34522100-3','scheme'=>'CAV','description'=>'Вітрильні човни','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'238','id'=>'39561000-2','scheme'=>'CAV','description'=>'Тюль, мереживо, вузькі тканини, оздоблювальні матеріали та вишиті вироби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'239','id'=>'32552520-8','scheme'=>'CAV','description'=>'Телексне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'240','id'=>'42131160-2','scheme'=>'CAV','description'=>'Гідранти','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'241','id'=>'32570000-9','scheme'=>'CAV','description'=>'Комунікаційне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'242','id'=>'34110000-1','scheme'=>'CAV','description'=>'Легкові автомобілі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'243','id'=>'42418290-8','scheme'=>'CAV','description'=>'Обладнання для гірськолижних підіймачів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'244','id'=>'34946110-4','scheme'=>'CAV','description'=>'Рейки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'245','id'=>'39291000-8','scheme'=>'CAV','description'=>'Пральне приладдя','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'246','id'=>'42900000-5','scheme'=>'CAV','description'=>'Універсальні та спеціалізовані машини різні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'247','id'=>'30216000-6','scheme'=>'CAV','description'=>'Магнітні та оптичні зчитувальні пристрої','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'248','id'=>'30124150-0','scheme'=>'CAV','description'=>'Фільтри для термофіксаторів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'249','id'=>'32342412-3','scheme'=>'CAV','description'=>'Динаміки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'250','id'=>'39113200-9','scheme'=>'CAV','description'=>'Дивани-канапе','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'251','id'=>'39226210-7','scheme'=>'CAV','description'=>'Бутлі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'252','id'=>'32352000-5','scheme'=>'CAV','description'=>'Антени та антенні відбивачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'253','id'=>'34133100-9','scheme'=>'CAV','description'=>'Автоцистерни','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'254','id'=>'34144450-7','scheme'=>'CAV','description'=>'Поливальні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'255','id'=>'34322300-3','scheme'=>'CAV','description'=>'Гальмові накладки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'256','id'=>'30191200-6','scheme'=>'CAV','description'=>'Графопроектори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'257','id'=>'30192152-1','scheme'=>'CAV','description'=>'Нумератори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'258','id'=>'30233151-4','scheme'=>'CAV','description'=>'Пристрої для читання та/або запису компакт-дисків (CD)','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'259','id'=>'42512200-0','scheme'=>'CAV','description'=>'Настінні кондиціонери повітря','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'260','id'=>'34139200-2','scheme'=>'CAV','description'=>'Шасі для кузова','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'261','id'=>'32237000-3','scheme'=>'CAV','description'=>'Портативні радіостанції','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'262','id'=>'42533000-1','scheme'=>'CAV','description'=>'Частини теплових насосів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'263','id'=>'34912100-4','scheme'=>'CAV','description'=>'Прогулянкові дитячі візки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'264','id'=>'42716200-0','scheme'=>'CAV','description'=>'Сушильні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'265','id'=>'30237300-2','scheme'=>'CAV','description'=>'Комп’ютерне приладдя','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'266','id'=>'32310000-9','scheme'=>'CAV','description'=>'Радіоприймачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'267','id'=>'42215120-3','scheme'=>'CAV','description'=>'Беконорізки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'268','id'=>'42998100-9','scheme'=>'CAV','description'=>'Системи автоматизованого повернення піддонів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'269','id'=>'39298800-5','scheme'=>'CAV','description'=>'Акваріуми','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'270','id'=>'39226300-5','scheme'=>'CAV','description'=>'Шпульки чи котушки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'271','id'=>'30199310-6','scheme'=>'CAV','description'=>'Тиснений або перфорований папір для друку','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'272','id'=>'34514900-2','scheme'=>'CAV','description'=>'Бурові платформи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'273','id'=>'34121000-1','scheme'=>'CAV','description'=>'Міські та туристичні автобуси','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'274','id'=>'32252100-5','scheme'=>'CAV','description'=>'Мобільні телефони з гарнітурою «вільні руки»','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'275','id'=>'39112100-1','scheme'=>'CAV','description'=>'Стільці для їдалень','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'276','id'=>'04234000-7','scheme'=>'CAV','description'=>'адміністративні приміщення в цокольних, підвальних, мансардних частинах будівлі ','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'277','id'=>'34612200-2','scheme'=>'CAV','description'=>'Вагони канатної дороги','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'278','id'=>'39721400-6','scheme'=>'CAV','description'=>'Неелектричні проточні чи акумуляційні водонагрівачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'279','id'=>'42113161-7','scheme'=>'CAV','description'=>'Осушувачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'280','id'=>'34390000-7','scheme'=>'CAV','description'=>'Приладдя до тракторів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'281','id'=>'42513200-7','scheme'=>'CAV','description'=>'Холодильне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'282','id'=>'42222000-8','scheme'=>'CAV','description'=>'Частини машин для виробництва напоїв','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'283','id'=>'04115100-8','scheme'=>'CAV','description'=>'Котедж','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'284','id'=>'32343100-0','scheme'=>'CAV','description'=>'Підсилювачі звукових частот','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'285','id'=>'42642400-2','scheme'=>'CAV','description'=>'Верстати для обробки ебоніту','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'286','id'=>'34144431-8','scheme'=>'CAV','description'=>'Підмітально-збиральні машини з вакуумно-пневматичною системою','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'287','id'=>'42942000-1','scheme'=>'CAV','description'=>'Печі та приладдя до них','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'288','id'=>'39721410-9','scheme'=>'CAV','description'=>'Газові прилади','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'289','id'=>'39151300-8','scheme'=>'CAV','description'=>'Модульні меблі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'290','id'=>'42671100-1','scheme'=>'CAV','description'=>'Тримачі лабораторних інструментів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'291','id'=>'34522150-8','scheme'=>'CAV','description'=>'Вітрильні катамарани','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'292','id'=>'42141410-3','scheme'=>'CAV','description'=>'Лебідки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'293','id'=>'39831100-7','scheme'=>'CAV','description'=>'Диспергатори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'294','id'=>'39295400-0','scheme'=>'CAV','description'=>'Ціпки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'295','id'=>'32332300-2','scheme'=>'CAV','description'=>'Звукозаписувальні пристрої','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'296','id'=>'34223350-4','scheme'=>'CAV','description'=>'Причепи з поворотними драбинами','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'297','id'=>'34943000-9','scheme'=>'CAV','description'=>'Системи контролю руху поїздів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'298','id'=>'39221110-1','scheme'=>'CAV','description'=>'Посуд','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'299','id'=>'06060000-0','scheme'=>'CAV','description'=>'Землі рекреаційного призначення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'300','id'=>'42913500-4','scheme'=>'CAV','description'=>'Повітрозабірні фільтри','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'301','id'=>'39516120-9','scheme'=>'CAV','description'=>'Подушки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'302','id'=>'32235000-9','scheme'=>'CAV','description'=>'Системи відеоспостереження замкнутого типу','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'303','id'=>'42718100-3','scheme'=>'CAV','description'=>'Прасувальні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'304','id'=>'42510000-4','scheme'=>'CAV','description'=>'Теплообмінники, кондиціонери повітря, холодильне обладнання та фільтрувальні пристрої','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'305','id'=>'42418220-7','scheme'=>'CAV','description'=>'Крісельні підіймачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'306','id'=>'34100000-8','scheme'=>'CAV','description'=>'Мототранспортні засоби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'307','id'=>'30193800-6','scheme'=>'CAV','description'=>'Затискачі для папірців-записок','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'308','id'=>'34968000-0','scheme'=>'CAV','description'=>'Аеропортові системи спостереження та освітлення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'309','id'=>'34934000-3','scheme'=>'CAV','description'=>'Гребні гвинти','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'310','id'=>'42912320-1','scheme'=>'CAV','description'=>'Деаераційні апарати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'311','id'=>'32323400-7','scheme'=>'CAV','description'=>'Відеовідтворювальне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'312','id'=>'42642500-3','scheme'=>'CAV','description'=>'Верстати для обробки твердих пластмас','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'313','id'=>'39717000-1','scheme'=>'CAV','description'=>'Вентилятори та кондиціонери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'314','id'=>'30192150-7','scheme'=>'CAV','description'=>'Датери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'315','id'=>'30123600-3','scheme'=>'CAV','description'=>'Монетні автомати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'316','id'=>'42418300-2','scheme'=>'CAV','description'=>'Устаткування для демонтажу факельних наконечників','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'317','id'=>'30192900-0','scheme'=>'CAV','description'=>'Корегувальні засоби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'318','id'=>'34522000-2','scheme'=>'CAV','description'=>'прогулянкові та спортивні човни','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'319','id'=>'42215000-6','scheme'=>'CAV','description'=>'Машини для промислової обробки чи виробництва продуктів харчування чи напоїв','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'320','id'=>'34913500-5','scheme'=>'CAV','description'=>'Автомобільні замки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'321','id'=>'39111000-3','scheme'=>'CAV','description'=>'Сидіння','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'322','id'=>'16300000-8','scheme'=>'CAV','description'=>'Збиральні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'323','id'=>'39518100-7','scheme'=>'CAV','description'=>'Штори для операційної зали','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'324','id'=>'30233153-8','scheme'=>'CAV','description'=>'Пристрої для читання та/або запису компакт-дисків (CD) та універсальних цифрових дисків (DVD)','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'325','id'=>'30215100-0','scheme'=>'CAV','description'=>'Центральні процесорні пристрої для мікрокомп’ютерів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'326','id'=>'42672000-7','scheme'=>'CAV','description'=>'Кріпильні механізми для верстатів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'327','id'=>'39721100-3','scheme'=>'CAV','description'=>'Побутові прилади для готування їжі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'328','id'=>'42112210-9','scheme'=>'CAV','description'=>'Водяні колеса','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'329','id'=>'42995200-9','scheme'=>'CAV','description'=>'Машини для прибирання пляжів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'330','id'=>'34947200-9','scheme'=>'CAV','description'=>'Частини шпал','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'331','id'=>'30233150-7','scheme'=>'CAV','description'=>'Оптичні накопичувачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'332','id'=>'42123610-3','scheme'=>'CAV','description'=>'Компресорні блоки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'333','id'=>'42123600-0','scheme'=>'CAV','description'=>'Поршневі об’ємні компресори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'334','id'=>'39721411-6','scheme'=>'CAV','description'=>'Газові нагрівачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'335','id'=>'34324000-4','scheme'=>'CAV','description'=>'Колеса, частини та приладдя до них','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'336','id'=>'42152200-8','scheme'=>'CAV','description'=>'Деталі корпусів ядерних реакторів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'337','id'=>'34328000-2','scheme'=>'CAV','description'=>'Випробувальні стенди, набори для переобладнання автомобіля та паси безпеки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'338','id'=>'30237450-8','scheme'=>'CAV','description'=>'Графічні планшети','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'339','id'=>'42996500-9','scheme'=>'CAV','description'=>'Ґрати для фільтрування стічних вод','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'340','id'=>'30194810-6','scheme'=>'CAV','description'=>'Рейсшини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'341','id'=>'34514800-1','scheme'=>'CAV','description'=>'Стаціонарні морські платформи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'342','id'=>'30213000-5','scheme'=>'CAV','description'=>'Персональні комп’ютери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'343','id'=>'39822000-0','scheme'=>'CAV','description'=>'Каустичні очищувачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'344','id'=>'30238000-6','scheme'=>'CAV','description'=>'Автоматизоване бібліотечне устаткування','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'345','id'=>'39141100-3','scheme'=>'CAV','description'=>'Полиці','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'346','id'=>'39224340-3','scheme'=>'CAV','description'=>'Відра для сміття','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'347','id'=>'34144212-7','scheme'=>'CAV','description'=>'Пожежні автоцистерни','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'348','id'=>'34711400-8','scheme'=>'CAV','description'=>'Літальні апарати спеціального призначення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'349','id'=>'34941200-7','scheme'=>'CAV','description'=>'Рейкові колії','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'350','id'=>'42522100-2','scheme'=>'CAV','description'=>'Частини вентиляторів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'351','id'=>'34994000-1','scheme'=>'CAV','description'=>'Освітлювальна апаратура для морської навігації та зовнішнього освітлення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'352','id'=>'42933200-7','scheme'=>'CAV','description'=>'Автомати для продажу марок','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'353','id'=>'42512300-1','scheme'=>'CAV','description'=>'Агрегати для опалення, вентилювання та кондиціювання повітря','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'354','id'=>'34513000-6','scheme'=>'CAV','description'=>'Риболовні, рятувальні та інші спеціальні судна','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'355','id'=>'07220000-7','scheme'=>'CAV','description'=>'Кредити Фізичних осіб заставні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'356','id'=>'42215100-7','scheme'=>'CAV','description'=>'Машини для нарізання продуктів харчування','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'357','id'=>'42980000-9','scheme'=>'CAV','description'=>'Газогенератори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'358','id'=>'39290000-1','scheme'=>'CAV','description'=>'Фурнітура різна','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'359','id'=>'32531000-4','scheme'=>'CAV','description'=>'Обладнання супутникового зв’язку','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'360','id'=>'42924740-8','scheme'=>'CAV','description'=>'Очисні апарати високого тиску','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'361','id'=>'30216130-6','scheme'=>'CAV','description'=>'Сканери штрих-кодів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'362','id'=>'34612000-0','scheme'=>'CAV','description'=>'Локомотивні тендери та вагони канатної дороги','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'363','id'=>'42942200-3','scheme'=>'CAV','description'=>'Вакуумні печі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'364','id'=>'39515000-5','scheme'=>'CAV','description'=>'Штори, портьєри, кухонні штори та тканинні жалюзі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'365','id'=>'05092000-6','scheme'=>'CAV','description'=>'М\'ясопереробні підприємства','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'366','id'=>'39561140-5','scheme'=>'CAV','description'=>'Декоративні оздоблювальні матеріали','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'367','id'=>'42992100-7','scheme'=>'CAV','description'=>'Клітки Фарадея','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'368','id'=>'42419800-4','scheme'=>'CAV','description'=>'Частини конвеєрів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'369','id'=>'39142000-9','scheme'=>'CAV','description'=>'Садові меблі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'370','id'=>'42122161-3','scheme'=>'CAV','description'=>'Насоси водяного охолодження','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'371','id'=>'34400000-1','scheme'=>'CAV','description'=>'Мотоцикли, велосипеди та коляски','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'372','id'=>'39514200-0','scheme'=>'CAV','description'=>'Кухонні рушники','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'373','id'=>'39241000-3','scheme'=>'CAV','description'=>'Ножі та ножиці','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'374','id'=>'32221000-8','scheme'=>'CAV','description'=>'Радіомаяки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'375','id'=>'39120000-9','scheme'=>'CAV','description'=>'Столи, серванти, письмові столи та книжкові шафи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'376','id'=>'39171000-1','scheme'=>'CAV','description'=>'Вітрини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'377','id'=>'39831210-1','scheme'=>'CAV','description'=>'Мийні засоби для посудомийних машин','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'378','id'=>'34114400-3','scheme'=>'CAV','description'=>'Мікроавтобуси','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'379','id'=>'30216120-3','scheme'=>'CAV','description'=>'Пристрої для оптичного розпізнавання символів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'380','id'=>'42419540-3','scheme'=>'CAV','description'=>'Частини пасажирських конвеєрів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'381','id'=>'30193900-7','scheme'=>'CAV','description'=>'Пюпітри для документів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'382','id'=>'34998000-9','scheme'=>'CAV','description'=>'Регулювальне, запобіжне чи сигнальне обладнання портових споруд','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'383','id'=>'34730000-3','scheme'=>'CAV','description'=>'Частини повітряних і космічних літальних апаратів та вертольотів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'384','id'=>'32412120-1','scheme'=>'CAV','description'=>'Мережа Інтранет','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'385','id'=>'42513220-3','scheme'=>'CAV','description'=>'Холодильні прилавки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'386','id'=>'42962500-2','scheme'=>'CAV','description'=>'Гравірувальні верстати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'387','id'=>'32324310-6','scheme'=>'CAV','description'=>'Супутникові антени','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'388','id'=>'39000000-2','scheme'=>'CAV','description'=>'Меблі (у тому числі офісні меблі), меблево-декоративні вироби, побутова техніка (крім освітлювального обладнання) та засоби для чищення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'389','id'=>'34144750-0','scheme'=>'CAV','description'=>'Вантажоперевізні транспортні засоби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'390','id'=>'34144511-3','scheme'=>'CAV','description'=>'Сміттєзбиральні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'391','id'=>'39224300-1','scheme'=>'CAV','description'=>'Мітли, щітки та інше прибиральне приладдя','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'392','id'=>'32420000-3','scheme'=>'CAV','description'=>'Мережеве обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'393','id'=>'30213100-6','scheme'=>'CAV','description'=>'Портативні комп’ютери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'394','id'=>'39222120-1','scheme'=>'CAV','description'=>'Стакани одноразового використання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'395','id'=>'42994220-8','scheme'=>'CAV','description'=>'Приладдя для ламінації','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'396','id'=>'42674000-1','scheme'=>'CAV','description'=>'Частини та приладдя до металообробних верстатів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'397','id'=>'05040000-7','scheme'=>'CAV','description'=>'Торгівельно-розважальні комплекси','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'398','id'=>'39145000-0','scheme'=>'CAV','description'=>'Інвентар для винних льохів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'399','id'=>'42924730-5','scheme'=>'CAV','description'=>'Апарати для миття водою під тиском','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'400','id'=>'30192320-0','scheme'=>'CAV','description'=>'Стрічка для принтерів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'401','id'=>'30212000-8','scheme'=>'CAV','description'=>'Апаратне забезпечення мінікомп’ютерів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'402','id'=>'42715000-1','scheme'=>'CAV','description'=>'Швейні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'403','id'=>'34930000-5','scheme'=>'CAV','description'=>'Суднове обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'404','id'=>'30233152-1','scheme'=>'CAV','description'=>'Пристрої для читання та/або запису універсальних цифрових дисків (DVD)','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'405','id'=>'39561130-2','scheme'=>'CAV','description'=>'Текстильні етикетки і нашивки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'406','id'=>'30214000-2','scheme'=>'CAV','description'=>'Робочі станції','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'407','id'=>'42213000-2','scheme'=>'CAV','description'=>'Машини, що використовуються у виробництві алкогольних або фруктових напоїв','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'408','id'=>'30199792-8','scheme'=>'CAV','description'=>'Календарі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'409','id'=>'39254130-7','scheme'=>'CAV','description'=>'Годинникове скло','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'410','id'=>'42131144-4','scheme'=>'CAV','description'=>'Клапани регулювання процесів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'411','id'=>'32552330-9','scheme'=>'CAV','description'=>'Телефонні комутаційні апарати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'412','id'=>'30195500-7','scheme'=>'CAV','description'=>'Дошки для крейди чи приладдя','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'413','id'=>'34139300-3','scheme'=>'CAV','description'=>'Суцільні шасі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'414','id'=>'39812000-7','scheme'=>'CAV','description'=>'Поліролі та креми','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'415','id'=>'32423000-4','scheme'=>'CAV','description'=>'Мережеві концентратори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'416','id'=>'42995000-7','scheme'=>'CAV','description'=>'Очисні машини різні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'417','id'=>'42931120-8','scheme'=>'CAV','description'=>'Настільні центрифуги','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'418','id'=>'30195100-3','scheme'=>'CAV','description'=>'Планувальні дошки чи приладдя','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'419','id'=>'34513300-9','scheme'=>'CAV','description'=>'Морські плавучі доки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'420','id'=>'42959000-3','scheme'=>'CAV','description'=>'Непобутові посудомийні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'421','id'=>'42961300-3','scheme'=>'CAV','description'=>'Системи визначання місцезнаходження транспортних засобів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'422','id'=>'39113100-8','scheme'=>'CAV','description'=>'М’які крісла','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'423','id'=>'30213500-0','scheme'=>'CAV','description'=>'Кишенькові комп’ютери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'424','id'=>'39820000-6','scheme'=>'CAV','description'=>'Органічні поверхнево активні речовини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'425','id'=>'42675000-8','scheme'=>'CAV','description'=>'Частини та приладдя до верстатів для обробки твердих матеріалів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'426','id'=>'42122420-7','scheme'=>'CAV','description'=>'Підіймачі рідин','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'427','id'=>'32200000-5','scheme'=>'CAV','description'=>'Передавальна апаратура для радіотелефонії, радіотелеграфії, радіомовлення і телебачення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'428','id'=>'30197330-8','scheme'=>'CAV','description'=>'Діроколи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'429','id'=>'34310000-3','scheme'=>'CAV','description'=>'Двигуни та їх частини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'430','id'=>'39254100-8','scheme'=>'CAV','description'=>'Годинники','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'431','id'=>'30192160-0','scheme'=>'CAV','description'=>'Коректори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'432','id'=>'42999300-8','scheme'=>'CAV','description'=>'Частини промислових пилососів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'433','id'=>'42124330-3','scheme'=>'CAV','description'=>'Частини повітряних компресорів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'434','id'=>'39132300-9','scheme'=>'CAV','description'=>'Картотеки для підвісних файлів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'435','id'=>'32331600-8','scheme'=>'CAV','description'=>'MP3-плеєри','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'436','id'=>'30131300-9','scheme'=>'CAV','description'=>'Адресувальні пристрої','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'437','id'=>'39154000-6','scheme'=>'CAV','description'=>'Виставкове обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'438','id'=>'32552100-8','scheme'=>'CAV','description'=>'Телефони','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'439','id'=>'42921330-0','scheme'=>'CAV','description'=>'Обгортальні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'440','id'=>'34512800-7','scheme'=>'CAV','description'=>'Танкери','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'441','id'=>'39222000-4','scheme'=>'CAV','description'=>'Приладдя для закладів громадського харчування','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'442','id'=>'34144211-0','scheme'=>'CAV','description'=>'Пожежні автомобілі з поворотною драбиною','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'443','id'=>'16611000-1','scheme'=>'CAV','description'=>'Машини для очищення сільськогосподарської продукції','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'444','id'=>'32236000-6','scheme'=>'CAV','description'=>'Радіотелефони','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'445','id'=>'39522541-1','scheme'=>'CAV','description'=>'Пухові чи пір’яні спальні мішки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'446','id'=>'30237350-7','scheme'=>'CAV','description'=>'Картриджі даних','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'447','id'=>'34913300-3','scheme'=>'CAV','description'=>'Автомобільні крила','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'448','id'=>'39563520-7','scheme'=>'CAV','description'=>'Конвеєрні стрічки з текстильних матеріалів','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'449','id'=>'42123400-8','scheme'=>'CAV','description'=>'Повітряні компресори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'450','id'=>'42131145-1','scheme'=>'CAV','description'=>'Клапани, затвори зворотні ','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'451','id'=>'30197600-2','scheme'=>'CAV','description'=>'Оброблені папір і картон','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'452','id'=>'39241130-3','scheme'=>'CAV','description'=>'Багатофункціональні ножі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'453','id'=>'42131270-6','scheme'=>'CAV','description'=>'Коркові крани','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'454','id'=>'30237253-7','scheme'=>'CAV','description'=>'Чохли для комп’ютерного обладнання для захисту від пилу','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'456','id'=>'39100000-3','scheme'=>'CAV','description'=>'39100000-3','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'457','id'=>'05010000-8','scheme'=>'CAV','description'=>'TEST','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'458','id'=>'34946200-2','scheme'=>'CAV','description'=>'Опис об\'єкту з кодом 66113000-5 за класифікаторм CPV, хоча повинно бути за CAV','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'459','id'=>'34111200-0','scheme'=>'CAV','description'=>'Легкові автомобілі типу «седан»','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'460','id'=>'04200000-0','scheme'=>'CAV','description'=>'Комерційна нерухомість','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'461','id'=>'04210000-3','scheme'=>'CAV','description'=>'Промислова нерухомість','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'462','id'=>'05095000-7','scheme'=>'CAV','description'=>'05095000-7','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'463','id'=>'30192134-9','scheme'=>'CAV','description'=>'Підставки для олівців','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'464','id'=>'30121100-4','scheme'=>'CAV','description'=>'Фотокопіювальні пристрої','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'465','id'=>'30110000-3','scheme'=>'CAV','description'=>'Текстообробні системи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'466','id'=>'30192153-8','scheme'=>'CAV','description'=>'Штампи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'467','id'=>'30132200-5','scheme'=>'CAV','description'=>'Купюрорахувальні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'468','id'=>'04111220-7','scheme'=>'CAV','description'=>'Житловий будинок барачного типу','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'469','id'=>'04111210-4','scheme'=>'CAV','description'=>'Елінг','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'470','id'=>'32344280-2','scheme'=>'CAV','description'=>'Рації','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'471','id'=>'32344200-8','scheme'=>'CAV','description'=>'Радіоприймачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'472','id'=>'07126000-8','scheme'=>'CAV','description'=>'Застава - Транспортне обладнання та допоміжне приладдя до нього','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'473','id'=>'30121400-7','scheme'=>'CAV','description'=>'Механічні копіювальні апарати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'474','id'=>'39225720-8','scheme'=>'CAV','description'=>'Банки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'475','id'=>'06090000-9','scheme'=>'CAV','description'=>'Землі водного фонду','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'476','id'=>'05050000-0','scheme'=>'CAV','description'=>'Офісні та бізнес центри','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'477','id'=>'16700000-2','scheme'=>'CAV','description'=>'Трактори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'478','id'=>'16320000-4','scheme'=>'CAV','description'=>'Сінозбиральні машини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'479','id'=>'16620000-7','scheme'=>'CAV','description'=>'Доїльні апарати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'480','id'=>'30132000-3','scheme'=>'CAV','description'=>'Сортувальне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'487','id'=>'30192000-1','scheme'=>'CAV','description'=>'Офісне приладдя','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'488','id'=>'34144400-2','scheme'=>'CAV','description'=>'Транспортні засоби для утримання доріг','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'489','id'=>'30192130-1','scheme'=>'CAV','description'=>'Олівці','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'490','id'=>'16110000-9','scheme'=>'CAV','description'=>'Плуги чи дискові борони','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'491','id'=>'16311000-8','scheme'=>'CAV','description'=>'Газонокосарки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'492','id'=>'04112300-9','scheme'=>'CAV','description'=>'Багаторівнева квартира','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'493','id'=>'34113300-5','scheme'=>'CAV','description'=>'Позашляхові засоби транспортні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'494','id'=>'30142200-8','scheme'=>'CAV','description'=>'Касові апарати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'495','id'=>'32572200-5','scheme'=>'CAV','description'=>'Комунікаційні кабелі з коаксіальними провідниками','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'496','id'=>'30199210-5','scheme'=>'CAV','description'=>'Поштові листівки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'497','id'=>'34150000-3','scheme'=>'CAV','description'=>'Транспортні симулятори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'498','id'=>'04113100-4','scheme'=>'CAV','description'=>'Комунальна квартира','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'499','id'=>'30122100-1','scheme'=>'CAV','description'=>'Цифрові системи для офсетного друку','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'500','id'=>'07210000-4','scheme'=>'CAV','description'=>'Кредити Фізичних осіб беззаставні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'501','id'=>'30121000-3','scheme'=>'CAV','description'=>'Фотокопіювальні та термокопіювальні пристрої','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'502','id'=>'30150000-5','scheme'=>'CAV','description'=>'Друкарські машинки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'503','id'=>'30150000-5','scheme'=>'CAV','description'=>'Друкарські машинки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'504','id'=>'30120000-6','scheme'=>'CAV','description'=>'Фотокопіювальне та поліграфічне обладнання для офсетного друку','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'505','id'=>'05070000-6','scheme'=>'CAV','description'=>'Готельні комплекси','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'506','id'=>'04114200-2','scheme'=>'CAV','description'=>'Будинок в садовому кооперативі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'507','id'=>'07123000-7','scheme'=>'CAV','description'=>'Застава - Земельні ділянки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'508','id'=>'34968200-2','scheme'=>'CAV','description'=>'Аеропортові системи освітлення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'509','id'=>'30197210-1','scheme'=>'CAV','description'=>'Теки-реєстратори','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'510','id'=>'42000000-6','scheme'=>'CAV','description'=>'Промислова техніка','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'511','id'=>'34711110-8','scheme'=>'CAV','description'=>'Повітряні літальні апарати з нерухомими крилами','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'512','id'=>'39132200-8','scheme'=>'CAV','description'=>'Багатошухлядні шафи-картотеки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'513','id'=>'39140000-5','scheme'=>'CAV','description'=>'Меблі для дому','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'514','id'=>'34969200-9','scheme'=>'CAV','description'=>'Літакові пересувні трапи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'515','id'=>'06010000-5','scheme'=>'CAV','description'=>'Землі сільськогосподарського призначення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'516','id'=>'39111100-4','scheme'=>'CAV','description'=>'Поворотні сидіння','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'517','id'=>'34946121-4','scheme'=>'CAV','description'=>'Рейкові накладки та підкладки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'518','id'=>'34711100-5','scheme'=>'CAV','description'=>'Літаки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'519','id'=>'34710000-7','scheme'=>'CAV','description'=>'Вертольоти, літаки, космічні та інші літальні апарати з двигуном','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'520','id'=>'30124140-7','scheme'=>'CAV','description'=>'Цілісні майнові крмплекси','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'521','id'=>'34711000-4','scheme'=>'CAV','description'=>'Вертольоти та літаки','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'522','id'=>'07221000-4','scheme'=>'CAV','description'=>'Застава - Нерухоме майно','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'523','id'=>'34913000-0','scheme'=>'CAV','description'=>'Запасні частини різні','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'524','id'=>'32300000-6','scheme'=>'CAV','description'=>'Радіо- і телевізійні приймачі, апаратура для запису та відтворення аудіо- та відеоматеріалу','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'525','id'=>'30177000-0','scheme'=>'CAV','description'=>'Автоматичні маркувальні системи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'526','id'=>'42600000-2','scheme'=>'CAV','description'=>'Верстати','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'527','id'=>'30200000-1','scheme'=>'CAV','description'=>'Комп’ютерне обладнання та приладдя','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'528','id'=>'04113200-5','scheme'=>'CAV','description'=>'Кімната в гуртожитку','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'529','id'=>'32344260-6','scheme'=>'CAV','description'=>'Радіо- та мультиплексне обладнання','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'530','id'=>'34114110-3','scheme'=>'CAV','description'=>'Рятувальні транспортні засоби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'531','id'=>'34114100-0','scheme'=>'CAV','description'=>'Аварійно-рятувальні транспортні засоби','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'532','id'=>'34114000-9','scheme'=>'CAV','description'=>'Транспортні засоби спеціального призначення','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'533','id'=>'30216200-8','scheme'=>'CAV','description'=>'Зчитувачі магнітних карток','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'534','id'=>'32323500-8','scheme'=>'CAV','description'=>'Системи відеоспостереження','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'535','id'=>'34910000-9','scheme'=>'CAV','description'=>'Гужові чи ручні вози, інші транспортні засоби з немеханічним приводом, багажні вози та різні запасні частини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'536','id'=>'04221000-3','scheme'=>'CAV','description'=>'торгово-розважальний комплекс, супермаркет, гіпермаркет тощо','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'537','id'=>'04221000-3','scheme'=>'CAV','description'=>'торгово-розважальний комплекс, супермаркет, гіпермаркет тощо','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'538','id'=>'42113390-1','scheme'=>'CAV','description'=>'Газопаливні системи','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'539','id'=>'42943300-1','scheme'=>'CAV','description'=>'Занурювані охолоджувачі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'540','id'=>'07224000-5','scheme'=>'CAV','description'=>'Застава - Сільськогосподарська техніка','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'541','id'=>'04211000-0','scheme'=>'CAV','description'=>'промислова заводська, фабрична будівля та їх частини','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'542','id'=>'42112300-7','scheme'=>'CAV','description'=>'Газові турбіни','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'543','id'=>'30210000-4','scheme'=>'CAV','description'=>'Машини для обробки даних (апаратна частина)','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'544','id'=>'04115000-7','scheme'=>'CAV','description'=>'садибний (індивідуальний) будинок малоповерхового житлового буді','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'545','id'=>'32551000-0','scheme'=>'CAV','description'=>'Телефонні кабелі та супутня продукція','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'546','id'=>'39518000-6','scheme'=>'CAV','description'=>'Лікарняна білизна','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'547','id'=>'30192110-5','scheme'=>'CAV','description'=>'Чорнила та пов’язана продукція','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'548','id'=>'39563200-8','scheme'=>'CAV','description'=>'Металізовані пряжі','uri'=>'']);
        $this->insert('{{%api_classifications}}',['unique_id'=>'549','id'=>'30141100-0','scheme'=>'CAV','description'=>'Кишенькові калькулятори','uri'=>'']);
        $this->execute('SET foreign_key_checks = 1;');
    }

    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        $this->execute('DROP TABLE IF EXISTS `api_classifications`');
        $this->execute('SET foreign_key_checks = 1;');
    }
}
