<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Ролі успішно призначені',
    'Auth item with such name already exists' => 'Елемент з таким ім’ям вже є',
    'Class "{0}" does not exist' => 'Клас "{0}" відсутній',
    'Classname of the rule associated with this item' => 'Ім’я класу правил, зв’язаних з цим елементом',
    'Create' => 'Створити',
    'Create new permission' => 'Створити новий дозвіл',
    'Create new role' => 'Створити нову роль',
    'Description' => 'Опис',
    'Invalid value' => 'Невірне значення',
    'Item has been created' => 'Пункт успішно створено',
    'Item has been updated' => 'Пункт успішно оновлений',
    'Name' => 'Ім’я',
    'New permission' => 'Новий дозвіл',
    'New role' => 'Нова роль',
    'New user' => 'Новий користувач',
    'Permissions' => 'Дозволи',
    'Roles' => 'Ролі',
    'Rule class can not be instantiated' => 'Об’єкт класу правил не може бути створений',
    'Rule class must extend "yii\rbac\Rule"' => 'Клас правил повинен бути наслідником класу  "yii\rbac\Rule"',
    'Rule name' => 'Правило',
    'Save' => 'Зберегти',
    'The item description (Optional).' => 'Опис (Не обов’язково)',
    'The name of the item.' => 'Ім’я елемента.',
    'There is neither role nor permission with name "{0}"' => 'Не існує ні ролей, ні дозволів з ім’ям "{0}"',
    'Update assignments' => 'Оновити призначення',
    'Update permission' => 'Оновити дозволи',
    'Update role' => 'Оновити роль',
    'Users' => 'Користувачі',
    'Сhildren' => 'Дочірні правила',
    'Rule' => 'Правило',
    'Children' => 'Дочірні',

];